POST http://demo.local.com/web/session/authenticate
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "jsonrpc": "2.0",
    "params": {
      "db": "demo",
      "login": "admin",
      "password": "admin"
    }
}

#> {% client.global.set("session_id", response.body.json.session_id); %}

### Use session id in next request for authorization
GET http://demo.local.com/altruja/create/1
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
#'X-Openerp-Session-Id': {{session_id}},

{
  "jsonrpc": "2.0",
    "params": {
      "vorname": "Michael",
      "nachname": "Karrer"
    }
}

###
